SUBDIRS = images

xgreetersdir = $(datadir)/xgreeters
dist_xgreeters_DATA = gooroom-greeter.desktop

greeter_scriptsdir = $(pkglibexecdir)
greeter_scripts_SCRIPTS = gis-user-delete-script

configdir = $(pkgdatadir)
dist_config_DATA = gooroom-greeter.conf

lightdm_datadir = $(datadir)/lightdm/lightdm.conf.d
lightdm_data_DATA = \
	90_gooroom-greeter.conf
